### ISSUE TITLE
no zlib.h

### ISSUE THREAD

**Issue by dronesalot** [chmorgan/libesphttpd#15]
I've installed it as directed into the current esp-idf library. This is using a windows install as directed in the expressif instructions. esp-idf examples and such build and work correctly so I don't suspect it is the toolchain per se.

/home/miker/esp/esp-idf/components/libesphttpd/espfs/mkespfsimage//main.c:30:18: fatal error: zlib.h: No such file or directory

**Comment by chmorgan** [comment]
Looks like you need the zlib development package installed. What linux
distro?



On Thu, Mar 22, 2018 at 11:41 PM, Michael Richards <notifications@github.com

**Comment by dronesalot** [comment]
It is not a linux distro at all, it's using the windows toolchain. I think the best solution may be to embed a zlib copy in the package, provided it is license-compatible.

**Comment by chmorgan** [comment]
Hmm. I’m not a frequent windows user. It could be possible to add zlib as a
submodule. How do other projects handle build dependencies on windows?

**Comment by valkuc** [comment]
Compile under cygwin. I'm using this UDK https://github.com/CHERTS/esp8266-devkit

**Comment by chmorgan** [comment]
Hey, long time!

Should we add a note to the readme.md about building under windows?

**Comment by valkuc** [comment]
Well, actually I don't know. @fastworks use esp-idf for ESP32 development. I'm using UDK for ESP8266 development as there is no official SDK for Windows and it's built on top of Cygwin. Unfortunately I'm not familiar with esp-idf so can't suggest. Maybe it's better to ask @Spritetm or @igrr

**Comment by dronesalot** [comment]
I'm not sure how dependencies are typically handled in windows as I'm more of a unix user. My project requires some windows based tools unfortunately. I think the best strategy for compatibility would be to include zlib as part of this component. I'm pretty sure there are non-GNU infected versions of zlib that could be included without conflicting with your license.

**Comment by edclombardo** [comment]
How does one initialize the http webserver from chmorgan/libesphttpd source code? httpdInit() is not found in the source code, where it is found in Spritetm/libesphttpd source code for ESP8266.  I am looking at using libesphttpd for ESP32 from chmorgan's git repository.  I found httpdFreertosInit() but it requires arguments that appear to me to be internal to the libesphttpd and not known in app_main().  Almost like httpdInit() is missing.  Any suggestions would be appreciated.  Also how to handle zlib on windows+eclipse.

**Comment by wdouglas1999** [comment]
Good day,
I am on Windows and have the same issue as fastworks. The issue of “no zlib” 
Is there any work around available for this ?
Thank you.

**Comment by phatpaul** [comment]
I figured it out.
In the esp-idf (mingw32.exe) install zlib-devel

```
$ pacman -S zlib-devel
```

Please add a note for windows users here:
https://github.com/chmorgan/libesphttpd/blob/master/espfs/mkespfsimage/main.c#L28
