### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by treii28** [chmorgan/libesphttpd#17]
Is there any kind of how-to or step-by-step anywhere on setting this up and installing it on an ESP? I haven't had much luck with the Arduino based captive portals when trying to access them from newer Android and Ios devices and I'm looking for other captive portal servers to try. But I downloaded this, the freeRTOS example and the freeRTOS SDK and I'm not sure how to plug all the pieces together.

**Comment by chmorgan** [comment]
Hi Scott.

There is an example project repo linked in the readme, have you taken a
look at that?

Also is this esp8266 or esp32? I’m only using esp32 here but the library
should still support esp8266.
