### ISSUE TITLE
Z_BEST_COMPRESSION'undeclared'

### ISSUE THREAD

**Issue by ataweg** [chmorgan/libesphttpd#34]
libesphttpd/espfs/mkespfsimage//main.c:339:18: error: 'Z_BEST_COMPRESSION'undeclared
    int compLvl = Z_BEST_COMPRESSION;
                  ^~~~~~~~~~~~~~~~~~
A known issue you have caught, when your don't use any compression.
Viele Gruesse
Axel

**Comment by chmorgan** [comment]
Hi @ataweg.

Fixed and pushed to master, thanks for reporting!
