### ISSUE TITLE
Incorrect mime type for "htm", should be the same as for "html"

### ISSUE THREAD

**Issue by dmcnaugh** [chmorgan/libesphttpd#5]
In `libesphttpd/core/httpd.c` there is an incorrect mime type for `"htm"`:
there is no such mime type as `text/htm`, this should be `text/html`, the same as for `"html"`

```
//The mappings from file extensions to mime types. If you need an extra mime type,
//add it here.
static const ICACHE_RODATA_ATTR MimeMap mimeTypes[]={
	{"htm", "text/htm"},
	{"html", "text/html"},
```

**Comment by chmorgan** [comment]
@dmcnaugh agreed, mind creating a PR to fix this?

**Comment by chmorgan** [comment]
Merged, thanks for the PR!
