### ISSUE TITLE
"continue" from function with tls enabled

### ISSUE THREAD

**Issue by 20162026** [chmorgan/libesphttpd#86]
with tls enabled im getting errors in [httpd-freertos.c](https://github.com/chmorgan/libesphttpd/blob/master/core/httpd-freertos.c) line 427 and 441,  looks like its trying to call `continue` from function, just replacing `continue` with `return` fixed the issue

**Comment by phatpaul** [comment]
Thanks for the report.
Looks like those were previously inside a `while(!shutdown){}`
It got refactored in 8cb0d824689425976971de77afea96ffe2b49279

Please submit a PR if you fix it.

**Comment by phatpaul** [comment]
fixed in #99
