### ISSUE TITLE
add github topics

### ISSUE THREAD

**Issue by phatpaul** [chmorgan/libesphttpd#95]
Consider adding some GitHub "Topics" to libesphttpd and esphttpd-freertos to get some more exposure and help.
Currently libesphttpd is only tagged with: https-server and http-server.

I searched and found these popular Topics that seem relevant:
- esp32
- esp8266
- esp-idf
- esp8266-webserver
- webserver
- websocket
- websocket-server

@chmorgan seems only repo owner can add these topics

**Comment by chmorgan** [comment]
Hi @phatpaul. I added those topics, do they look ok?

**Comment by phatpaul** [comment]
And add to the esphttpd-freertos repo too please.

**Comment by chmorgan** [comment]
@phatpaul done

**Comment by phatpaul** [comment]
Thanks :-)
